# Generated by Django 5.2.8 on 2025-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("primaryTitle", models.CharField(max_length=500)),
                ("originalTitle", models.CharField(max_length=500)),
                ("startYear", models.IntegerField(blank=True, null=True)),
                ("runtimeMinutes", models.IntegerField(blank=True, null=True)),
                ("genres", models.CharField(blank=True, max_length=200, null=True)),
                ("averageRating", models.FloatField(default=0.0)),
                ("numVotes", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "movies",
            },
        ),
    ]
